# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/agayatri123/Proyek-Analisa-Data/blob/main/Proyek_Analisis_Data.ipynb

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Anindita Gayatri
- **Email:** agayatri123@yahoo.co.id
- **ID Dicoding:** anindita_gayatri_ukA6

## Menentukan Pertanyaan Bisnis

- Bagaimana pola pergerakan bulanan nya penyewaan sepeda ?
- Penyewa sepeda seperti apa yang memiliki kontribusi lebih besar? Penyewa terdaftar (registered) atau non-registered (casual) ?

## Import Semua Packages/Library yang Digunakan
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# load the dataset
df_hour= pd.read_csv('sample_data/hour.csv')

"""**Insight:**
- Walau terdapat sumber pengambilan dataset yang terpercaya seperti UCI, Google Datasearch dan sebagainya, namun dipilih mengambil data dari Kaggle.
- Dipilih menggunakan cara upload dataset di Notebook di folder sample_data, walau ada pilihan lain seperti via URL, access ke github, dsb.

### Assessing Data
"""

# Melihat summary dari struktur data hour
df_hour.info()

# Melihat kolom mana saja yang Numeric
num_col=[]
for col in df_hour.columns:
    if(df_hour[col].dtypes!='object'):
        num_col.append(col)
        #print(f"There are total {len(num_col)} numerical columns in dataset")
print(num_col)

# Melihat kolom mana saja yang Categorical
cat_col=[]
for col in df_hour.columns:
    if(df_hour[col].dtypes=='object'):
        cat_col.append(col)
print(f"There are total {len(cat_col)} categorical columns in dataset")
print(cat_col)

# Check data yang terduplikasi
df_hour.duplicated().sum()

"""**Insight:**
- Kondisi Data
Total Baris Data: 17,379 entries
Memori yang Digunakan: 2.3+ MB

- Terdiri dari 17 kolom feature data yaitu
  - instant     (int64)  
  - dteday      (object)
  - season      (int64)  
  - yr          (int64)  
  - mnth        (int64)  
  - hr          (int64)  
  - holiday     (int64)  
  - weekday     (int64)  
  - workingday  (int64)  
  - weathersit  (int64)  
  - temp        (float64)
  - atemp       (float64)
  - hum         (float64)
  - windspeed   (float64)
  - casual      (int64)  
  - registered  (int64)  
  - cnt         (int64)

### Cleaning Data
"""

# Check missing value dengan fungsi isnull()
df_hour.isnull().sum()

# Men-drop data kosong walau sebenarnya tidak ditemukan data yang kosong
df_hour.dropna(axis=0, inplace=True)

# Men-drop data yang terduplikasi walau sebenarnya tidak ditemukan data yang terduplikasi
df_hour.drop_duplicates(inplace=True)

# Mengecek Season atau Musim yang unik
df_hour.season.unique()

"""**Insight:**
- Status missing values:
  - Tidak ada
- Walau tidak ada missing values dan duplikasi, tetap dilakukan cleaning. Sehingga hasilnya tetap sama karena tidak ada data yang ter-drop.
- Terdapat 4 musim yang unik, ditandai dengan penomoran 1,2, 3 dan 4.
"""



"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

df_hour.describe(include="all")

# Melihat distribusi data secara cepat
df_hour.hist()

# Mengelompokkan data
df_hour.groupby(by="mnth").max()

# Pembulatan kolom temperatur sesuai Celcius
df_hour["temp"] = df_hour["temp"]*100

# Melihat kembali kolom temp (temperatur) setelah dibuatkan sesuai Celcius
df_hour.groupby(by="mnth").max()

# Melihat urutan jumlah pemakai sepeda per hari dari urutan terbanyak
df_hour.sort_values(by="registered", ascending=False)

"""**Insight:**
- Kolom dteday tidak dapat dicari rata-rata, quartil atas, quartil bawah, max, dsb dikarenakan bukan data numeric. Melainkan data categorical.
- Saat melihat distribusi data secara cepat, karena kolom registered dan casual dibutuhkan untuk menjawab pertanyaan, maka saat dilihat ternyata distribusi nya tidak merata.
- Secara harian penyewaan ternyata TOP5 terjadi 3x di bulan Sep & 2x di bulan Nov.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Pada bulan apa pemakaian sewa sepeda terbanyak ?

# Penyajian bentuk Bar chart

plt.bar(x=df_hour['mnth'], height=df_hour['registered'], color='green')
plt.xticks(rotation=45)
plt.show()

"""### Pertanyaan 2:"""

# Lebih banyak mana penyewa sepeda dari yang sudah terdaftar (registered) dibandingkan penyewa yang tidak terdaftar (casual) ?

# Explanatory Analysis

import pandas as pd
df_hour['dteday'] = pd.to_datetime(df_hour['dteday'])

plt.figure(figsize=(12, 5))
plt.plot(df_hour['dteday'], df_hour['registered'], label='Penyewa Terdaftar', color='red')
plt.plot(df_hour['dteday'], df_hour['casual'], label='Penyewa Casual', color='blue')
plt.title('Jumlah Penyewa Sepeda Registered vs Casual', size=20)
plt.xlabel('dteday',size=15)
plt.ylabel('Jumlah',size=15)
plt.legend()
plt.show()

"""**Insight:**
- Ternyata penyewaan sepeda tertinggi terjadi di bulan 8,9 dan 10 yaitu Agustus, Sep dan Oct dimana ini adalah musim panas.  
- Ternyata didapatkan penyewa sepeda terdaftar (registered) konsisten selalu lebih banyak dibandingkan penyewa yang tidak terdaftar (casual) dalam musim apapun.
"""