# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3q7_0M5btZqcbc_vsqomurVRH-rFuRN

# Proyek Analisis Data: Persewaan Sepeda
- **Nama:** Anindita Gayatri
- **Email:** agayatri123@yahoo.co.id
- **ID Dicoding:** anindita_gayatri_ukA6
"""

!pip install pipreqs

from google.colab import drive
drive.mount('/content/drive')

pip freeze > requirements.txt

pip install streamlit

import streamlit as st

import matplotlib.pyplot as plt
import numpy as np
import streamlit as st

st.title('dashboard')
col1, col2 = st.columns(2)

with col1:
    st.header("Kolom 1")
    st.image("https://github.com/agayatri123/Proyek-Analisa-Data/blob/data/Submission/Data/Pic%201.jpg")

with col2:
    st.header("Kolom 2")
    st.image("https://github.com/agayatri123/Proyek-Analisa-Data/blob/data/Submission/Data/Pic%202.jpg")

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(35, 15))
colors = ["#90CAF9", "#90CAF9", "#90CAF9", "#90CAF9", "#90CAF9"]

st.pyplot(fig)

st.caption('Copyright (c) Anindita 2025')